# Generated by Django 3.0.5 on 2020-04-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addquote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=120)),
                ('customer_name', models.CharField(max_length=120)),
                ('lead_name', models.CharField(max_length=120)),
                ('term_type', models.CharField(max_length=120)),
                ('product', models.CharField(max_length=120)),
                ('penalties', models.CharField(max_length=120)),
            ],
        ),
    ]
