# Generated by Django 2.2.6 on 2020-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquote',
            name='o_url',
            field=models.URLField(default='Enter your url', max_length=1080),
        ),
        migrations.AlterField(
            model_name='addquote',
            name='lead_name',
            field=models.CharField(choices=[('Simon Woodford', 'Simon Woodford'), ('Vin Bolisetti', 'Vin Bolisetti')], max_length=56),
        ),
        migrations.AlterField(
            model_name='addquote',
            name='penalties',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='addquote',
            name='product',
            field=models.CharField(choices=[('OpenText ContentSuite', 'OpenText ContentSuite'), ('OpenText Experience Suite', 'OpenText Experience Suite'), ('OpenText Process Suite', 'OpenText Process Suite'), ('OpenText Information Exchange Suite', 'OpenText Information Exchange Suite'), ('OpenText Discovery Suite', 'OpenText Discovery Suite'), ('OpenText Suite for SAP', 'OpenText Suite for SAP'), ('OpenText Suite for Oracle', 'OpenText Suite for Oracle'), ('OpenText Suite for Microsoft', 'OpenText Suite for Microsoft'), ('OpenText Appworks', 'OpenText Appworks'), ('OpenText Cloud', 'OpenText Cloud')], max_length=120),
        ),
        migrations.AlterField(
            model_name='addquote',
            name='term_type',
            field=models.CharField(choices=[('Cloud Subscription', 'Cloud Subscription'), ('Cloud Perpetual', 'Cloud Perpetual'), ('SaaS', 'SaaS')], max_length=120),
        ),
    ]
